---
info:
  description: Training configuration repo1


---
spring:
  profile: cloud
  
eureka:
  client:
    serviceUrl:
      defaultZone: https://username:password@eureka-server-verificatory-bailey.cfapps.io/eureka
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    