spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/phillee238/configserver.git
          # ONLY include username and pwd if the repo is private
          username:
          password:
security:
  user:
    name: username
    password: password
          